# Shrink default JVM heap.
esJavaOpts: "-Xmx128m -Xms128m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"

replicas: 2

volumeClaimTemplate:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "nfs"
  resources:
    requests:
      storage: 1000M